error in action

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -15,5 +15,7 @@ jobs:
     steps:
   # Check-out your repository
       - uses: actions/checkout@v3
+      - name: To show error
+        run: echo "Should fail at this point ..." ; exit 1
       - name: Run a one-line script
-        run: echo "Continuous Integration"
+        run:  echo "Continuous Integration"
